name: "Deploy React App to EC2"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Debug Build Output
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of build directory:"
          ls -la build

      - name: Copy Files Via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "43.204.21.252"
          username: ubuntu
          key: ${{ secrets.orgzstackDevServer }}
          source: "build"
          target: "/var/www/personnece_frontend/personnece_frontend"
